name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      #- name: Run tests
       # run: npm test  # Or comment out if you don’t have tests

      - name: Deploy to Render via Hook
        run: |
          export PORT="${{ secrets.PORT }}"
          export APP_NAME="${{ secrets.APP_NAME }}"
          echo "Deploying $APP_NAME on port $PORT"
          curl "${{ secrets.RENDER_DEPLOY_HOOK }}"
